In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv("./../data/b-ner.csv", encoding="utf-8").fillna(method="ffill")

In [ ]:
data['Tag'] = data['Tag'].replace(['B-per','I-per','B-geo','I-geo','B-org','I-org','B-nat','I-nat','B-gpe','I-gpe','B-art','I-art','B-tim','I-tim','B-eve','I-eve'],['B-PER','I-PER','B-LOC','I-LOC','B-ORG','I-ORG','O','O','O','O','O','O','O','O','O','O'])
data

             Sentence #         Word    Tag
0           Sentence: 1    বাংলাদেশে  B-LOC
1           Sentence: 1    কক্সবাজার  B-LOC
2           Sentence: 1      এলাকায়      O
3           Sentence: 1  রোহিঙ্গাদের      O
4           Sentence: 1         জন্য      O
...                 ...          ...    ...
297412  Sentence: 22144    পরিবেশনাও      O
297413  Sentence: 22144         নাকি      O
297414  Sentence: 22144          আরও      O
297415  Sentence: 22144         বেশি      O
297416  Sentence: 22144         উষ্ণ      O

[297417 rows x 3 columns]

In [ ]:
len(data)

297417

In [ ]:
data.Tag.value_counts()

O        258289
B-LOC     10421
B-PER      9201
I-PER      9024
B-ORG      5465
I-ORG      4322
I-LOC       695
Name: Tag, dtype: int64

In [ ]:
word_list=[]
tag_list=[]
sentence_list=[]
word_list_sentence=[]
tag_list_sentence=[]
tuple_list=[]
tuple_list_sent=[]

In [ ]:
class SentenceGetter(object):

    def __init__(self, data):
        self.n_sent = 1
        self.data = data
        self.empty = False
        agg_func = lambda s: [(w, t) for w, t in zip(s["Word"].values.tolist(),
                                                           s["Tag"].values.tolist())]
        self.grouped = self.data.groupby("Sentence #").apply(agg_func)
        self.sentences = [s for s in self.grouped]

    def get_next(self):
        try:
            s = self.grouped["Sentence: {}".format(self.n_sent)]
            self.n_sent += 1
            return s
        except:
            return None

In [ ]:
getter = SentenceGetter(data)

In [ ]:
sent = getter.get_next()

In [ ]:
print(sent)

[('বাংলাদেশে', 'B-LOC'), ('কক্সবাজার', 'B-LOC'), ('এলাকায়', 'O'), ('রোহিঙ্গাদের', 'O'), ('জন্য', 'O'), ('নির্ধারিত', 'O'), ('আশ্রয়', 'O'), ('শিবিরের', 'O'), ('বাইরে', 'O'), ('বেরুলে', 'O'), ('তাদের', 'O'), ('গ্রেপ্তার', 'O'), ('করা', 'O'), ('হবে', 'O'), ('বলে', 'O'), ('জানিয়েছেন', 'O'), ('পুলিশের', 'O'), ('মহাপরিদর্শক', 'O'), ('একেএম', 'B-PER'), ('শহীদুল', 'I-PER'), ('হক', 'I-PER')]

In [ ]:
sentences = getter.sentences

In [ ]:
sentences[0]

[('বাংলাদেশে', 'B-LOC'),
 ('কক্সবাজার', 'B-LOC'),
 ('এলাকায়', 'O'),
 ('রোহিঙ্গাদের', 'O'),
 ('জন্য', 'O'),
 ('নির্ধারিত', 'O'),
 ('আশ্রয়', 'O'),
 ('শিবিরের', 'O'),
 ('বাইরে', 'O'),
 ('বেরুলে', 'O'),
 ('তাদের', 'O'),
 ('গ্রেপ্তার', 'O'),
 ('করা', 'O'),
 ('হবে', 'O'),
 ('বলে', 'O'),
 ('জানিয়েছেন', 'O'),
 ('পুলিশের', 'O'),
 ('মহাপরিদর্শক', 'O'),
 ('একেএম', 'B-PER'),
 ('শহীদুল', 'I-PER'),
 ('হক', 'I-PER')]

In [ ]:
for i in range(len(sentences)):
    sentence_list.append(i)
    tuple_list.append(sentences[i])

In [ ]:
new_data = pd.DataFrame()

new_data['Sentence_no']= sentence_list
new_data['word_tag']= tuple_list

In [ ]:
new_data

       Sentence_no                                           word_tag
0                0  [(বাংলাদেশে, B-LOC), (কক্সবাজার, B-LOC), (এলাক...
1                1  [(তবে, O), (টিজার, O), (দেখে, O), (দর্শকদের, O...
2                2  [(কিংবা, O), (পিতা, O), (মাতা, O), (কন্যা, O),...
3                3  [(কিন্তু, O), (আজব, O), (ব্যাপার, O), (বাস্তবে...
4                4  [(বাংলাদেশও, B-LOC), (এর, O), (ব্যতিক্রম, O), ...
...            ...                                                ...
22139        22139  [(বাংলাদেশ, B-ORG), (ব্যাংকের, I-ORG), (অধীনে,...
22140        22140  [(সঠিক, O), (তথ্য, O), (পাওয়া, O), (গেলে, O), ...
22141        22141  [(এ, O), (কারণে, O), (বাংলাদেশ, B-LOC), (আন্তর...
22142        22142  [(সরকারের, O), (দক্ষ, O), (পরিচালনায়, O), (অর্...
22143        22143  [(সামাজিক, O), (সূচকগুলোর, O), (অগ্রগতিতে, O),...

[22144 rows x 2 columns]

In [ ]:
only_tags=[]

In [ ]:
for i in range(len(new_data)):
    objective_ouput_list = [item[1] for item in tuple_list[i]]
    only_tags.append(objective_ouput_list)

In [ ]:
def is_iterable(item):
    """tests whether `item` is an iterable that is not a string"""
    try:
        iter(item)
        return not isinstance(item, str)
    except TypeError:
        return False

def flatten(iterable):
    for item in iterable:
        if is_iterable(item):
            yield from flatten(item)
        else:
            yield item

In [ ]:
f_only_tags= list(flatten(only_tags))

In [ ]:
data.Tag.value_counts()

O        258289
B-LOC     10421
B-PER      9201
I-PER      9024
B-ORG      5465
I-ORG      4322
I-LOC       695
Name: Tag, dtype: int64

In [ ]:
new_data['only_tags'] =  only_tags

In [ ]:
# For words

only_words=[]

for i in range(len(new_data)):
    objective_ouput_list = [item[0] for item in tuple_list[i]]
    only_words.append(objective_ouput_list)

In [ ]:
new_data['only_words']= only_words

In [ ]:
new_data

,Sentence_no,word_tag,only_tags,only_words
0,0,"[(বাংলাদেশে, B-LOC), (কক্সবাজার, B-LOC), (এলাক...","[B-LOC, B-LOC, O, O, O, O, O, O, O, O, O, O, O...","[বাংলাদেশে, কক্সবাজার, এলাকায়, রোহিঙ্গাদের, জ..."
1,1,"[(তবে, O), (টিজার, O), (দেখে, O), (দর্শকদের, O...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[তবে, টিজার, দেখে, দর্শকদের, বোঝার, উপায়, নেই,..."
2,2,"[(কিংবা, O), (পিতা, O), (মাতা, O), (কন্যা, O),...","[O, O, O, O, O, O, O, O, O, O]","[কিংবা, পিতা, মাতা, কন্যা, ছেলে, ভাই, বোন, স্ব..."
3,3,"[(কিন্তু, O), (আজব, O), (ব্যাপার, O), (বাস্তবে...","[O, O, O, O, O, O]","[কিন্তু, আজব, ব্যাপার, বাস্তবে, এমনটা, হয়নি]"
4,4,"[(বাংলাদেশও, B-LOC), (এর, O), (ব্যতিক্রম, O), ...","[B-LOC, O, O, O]","[বাংলাদেশও, এর, ব্যতিক্রম, নয়]"
...,...,...,...,...
22139,22139,"[(বাংলাদেশ, B-ORG), (ব্যাংকের, I-ORG), (অধীনে,...","[B-ORG, I-ORG, O, O, O, O, O, O]","[বাংলাদেশ, ব্যাংকের, অধীনে, একটি, তদন্ত, কমিটি..."
22140,22140,"[(সঠিক, O), (তথ্য, O), (পাওয়া, O), (গেলে, O), ...","[O, O, O, O, O, O, O, O, O, O, O, O, B-PER, I-...","[সঠিক, তথ্য, পাওয়া, গেলে, জড়িতদের, বিরুদ্ধে, ব..."
22141,22141,"[(এ, O), (কারণে, O), (বাংলাদেশ, B-LOC), (আন্তর...","[O, O, B-LOC, O, O, O, O, O, O, O, O, O]","[এ, কারণে, বাংলাদেশ, আন্তর্জাতিক, সম্প্রদায়ের,..."
22142,22142,"[(সরকারের, O), (দক্ষ, O), (পরিচালনায়, O), (অর্...","[O, O, O, O, O, O, O, O, O, O]","[সরকারের, দক্ষ, পরিচালনায়, অর্থনীতির, সব, সূচক..."
22143,22143,"[(সামাজিক, O), (সূচকগুলোর, O), (অগ্রগতিতে, O),...","[O, O, O, B-LOC, O, O, O, O, O, O, O, O, O, O,...","[সামাজিক, সূচকগুলোর, অগ্রগতিতে, বাংলাদেশ, প্রত..."

In [ ]:
type(new_data['only_words'][0])

list

In [ ]:
only_sentence = []

In [ ]:
for i in range(len(new_data)):
    string_= " ".join(new_data['only_words'][i])
    only_sentence.append(string_)

In [ ]:
new_data['sentences'] = only_sentence

In [ ]:
new_data

,Sentence_no,word_tag,only_tags,only_words,sentences
0,0,"[(বাংলাদেশে, B-LOC), (কক্সবাজার, B-LOC), (এলাক...","[B-LOC, B-LOC, O, O, O, O, O, O, O, O, O, O, O...","[বাংলাদেশে, কক্সবাজার, এলাকায়, রোহিঙ্গাদের, জ...",বাংলাদেশে কক্সবাজার এলাকায় রোহিঙ্গাদের জন্য ন...
1,1,"[(তবে, O), (টিজার, O), (দেখে, O), (দর্শকদের, O...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[তবে, টিজার, দেখে, দর্শকদের, বোঝার, উপায়, নেই,...",তবে টিজার দেখে দর্শকদের বোঝার উপায় নেই যে ছবিত...
2,2,"[(কিংবা, O), (পিতা, O), (মাতা, O), (কন্যা, O),...","[O, O, O, O, O, O, O, O, O, O]","[কিংবা, পিতা, মাতা, কন্যা, ছেলে, ভাই, বোন, স্ব...",কিংবা পিতা মাতা কন্যা ছেলে ভাই বোন স্বামী স্ত্...
3,3,"[(কিন্তু, O), (আজব, O), (ব্যাপার, O), (বাস্তবে...","[O, O, O, O, O, O]","[কিন্তু, আজব, ব্যাপার, বাস্তবে, এমনটা, হয়নি]",কিন্তু আজব ব্যাপার বাস্তবে এমনটা হয়নি
4,4,"[(বাংলাদেশও, B-LOC), (এর, O), (ব্যতিক্রম, O), ...","[B-LOC, O, O, O]","[বাংলাদেশও, এর, ব্যতিক্রম, নয়]",বাংলাদেশও এর ব্যতিক্রম নয়
...,...,...,...,...,...
22139,22139,"[(বাংলাদেশ, B-ORG), (ব্যাংকের, I-ORG), (অধীনে,...","[B-ORG, I-ORG, O, O, O, O, O, O]","[বাংলাদেশ, ব্যাংকের, অধীনে, একটি, তদন্ত, কমিটি...",বাংলাদেশ ব্যাংকের অধীনে একটি তদন্ত কমিটি কাজ করছে
22140,22140,"[(সঠিক, O), (তথ্য, O), (পাওয়া, O), (গেলে, O), ...","[O, O, O, O, O, O, O, O, O, O, O, O, B-PER, I-...","[সঠিক, তথ্য, পাওয়া, গেলে, জড়িতদের, বিরুদ্ধে, ব...",সঠিক তথ্য পাওয়া গেলে জড়িতদের বিরুদ্ধে ব্যবস্থা...
22141,22141,"[(এ, O), (কারণে, O), (বাংলাদেশ, B-LOC), (আন্তর...","[O, O, B-LOC, O, O, O, O, O, O, O, O, O]","[এ, কারণে, বাংলাদেশ, আন্তর্জাতিক, সম্প্রদায়ের,...",এ কারণে বাংলাদেশ আন্তর্জাতিক সম্প্রদায়ের কাছে ...
22142,22142,"[(সরকারের, O), (দক্ষ, O), (পরিচালনায়, O), (অর্...","[O, O, O, O, O, O, O, O, O, O]","[সরকারের, দক্ষ, পরিচালনায়, অর্থনীতির, সব, সূচক...",সরকারের দক্ষ পরিচালনায় অর্থনীতির সব সূচকে উল্ল...
22143,22143,"[(সামাজিক, O), (সূচকগুলোর, O), (অগ্রগতিতে, O),...","[O, O, O, B-LOC, O, O, O, O, O, O, O, O, O, O,...","[সামাজিক, সূচকগুলোর, অগ্রগতিতে, বাংলাদেশ, প্রত...",সামাজিক সূচকগুলোর অগ্রগতিতে বাংলাদেশ প্রতিবেশী...

In [ ]:
type(new_data['only_words'][0])

list

In [ ]:
new_data.to_csv("./../data/ner_sentences.csv")

In [ ]:
testing = pd.read_csv("./../data/ner_sentences.csv")
type(testing['only_words'][0])

str

In [ ]:
## saving to json for this type change issue

new_data.to_json("./../data/ner_sent.json")

## see if the load json file works

import json

f= open("./ner_sent.json")

json_data = json.load(f)

# json_data

In [ ]:
## loading the json to dataframe and checking is it is ok

df = pd.read_json("./../data/ner_sent.json")
df.head(5)

,Sentence_no,word_tag,only_tags,only_words,sentences
0,0,"[[বাংলাদেশে, B-LOC], [কক্সবাজার, B-LOC], [এলাক...","[B-LOC, B-LOC, O, O, O, O, O, O, O, O, O, O, O...","[বাংলাদেশে, কক্সবাজার, এলাকায়, রোহিঙ্গাদের, জ...",বাংলাদেশে কক্সবাজার এলাকায় রোহিঙ্গাদের জন্য ন...
1,1,"[[তবে, O], [টিজার, O], [দেখে, O], [দর্শকদের, O...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[তবে, টিজার, দেখে, দর্শকদের, বোঝার, উপায়, নেই,...",তবে টিজার দেখে দর্শকদের বোঝার উপায় নেই যে ছবিত...
2,2,"[[কিংবা, O], [পিতা, O], [মাতা, O], [কন্যা, O],...","[O, O, O, O, O, O, O, O, O, O]","[কিংবা, পিতা, মাতা, কন্যা, ছেলে, ভাই, বোন, স্ব...",কিংবা পিতা মাতা কন্যা ছেলে ভাই বোন স্বামী স্ত্...
3,3,"[[কিন্তু, O], [আজব, O], [ব্যাপার, O], [বাস্তবে...","[O, O, O, O, O, O]","[কিন্তু, আজব, ব্যাপার, বাস্তবে, এমনটা, হয়নি]",কিন্তু আজব ব্যাপার বাস্তবে এমনটা হয়নি
4,4,"[[বাংলাদেশও, B-LOC], [এর, O], [ব্যতিক্রম, O], ...","[B-LOC, O, O, O]","[বাংলাদেশও, এর, ব্যতিক্রম, নয়]",বাংলাদেশও এর ব্যতিক্রম নয়

In [ ]:
type(df['only_words'][0])

list

In [ ]:
f_only_tags = set(f_only_tags)
f_only_tags

{'B-LOC', 'B-ORG', 'B-PER', 'I-LOC', 'I-ORG', 'I-PER', 'O'}

In [ ]:
data

             Sentence #         Word    Tag
0           Sentence: 1    বাংলাদেশে  B-LOC
1           Sentence: 1    কক্সবাজার  B-LOC
2           Sentence: 1      এলাকায়      O
3           Sentence: 1  রোহিঙ্গাদের      O
4           Sentence: 1         জন্য      O
...                 ...          ...    ...
297412  Sentence: 22144    পরিবেশনাও      O
297413  Sentence: 22144         নাকি      O
297414  Sentence: 22144          আরও      O
297415  Sentence: 22144         বেশি      O
297416  Sentence: 22144         উষ্ণ      O

[297417 rows x 3 columns]

**Another Dataframe for Tag-wise Word list from Used-Automation**

In [ ]:
g = data.groupby('Tag')['Word'].apply(set).reset_index(name='Words') # keeping in set and NOT list to avoid duplicate words.
g

     Tag                                              Words
0  B-LOC  {লালমোহন, রাখাইনে, কলকাতার, সুনাগঞ্জের, মিনায়,...
1  B-ORG  {এসিআই, ছাপরা, জিআইএন, বিজেপি, জাপা, পাবেসাস, ...
2  B-PER  {রাজনাথের, মারলন, মোঃ, ফেরদৌসের, দেল, সানজিদাদ...
3  I-LOC  {রাখাইনে, কোরিয়া৷, পিইন, রোড, লাউয়ে, জিল্যান্...
4  I-ORG  {সালভেশন, উদীচী, ফাউন্ডেশনের, উত্তরায়, ওয়াকর্স...
5  I-PER  {মান্নানের, মোঃ, সানজিদাদের, মায়োরালের, ইমামের...
6      O  {ফাঁকফোকরের, আদেশটি, পৌছে, রোড, সুচারুভাবে, নড়...

In [ ]:
g_set = g.set_index('Tag').T.to_dict('list')

In [ ]:
# g_set['B-per']

**Testing if the files load properly**

In [ ]:
import pandas as pd
test= pd.read_csv("./../data/ner_sentences.csv")
test

,Unnamed: 0,Sentence_no,word_tag,only_tags,only_words,sentences
0,0,0,"[('বাংলাদেশে', 'B-LOC'), ('কক্সবাজার', 'B-LOC'...","['B-LOC', 'B-LOC', 'O', 'O', 'O', 'O', 'O', 'O...","['বাংলাদেশে', 'কক্সবাজার', 'এলাকায়', 'রোহিঙ্গ...",বাংলাদেশে কক্সবাজার এলাকায় রোহিঙ্গাদের জন্য ন...
1,1,1,"[('তবে', 'O'), ('টিজার', 'O'), ('দেখে', 'O'), ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...","['তবে', 'টিজার', 'দেখে', 'দর্শকদের', 'বোঝার', ...",তবে টিজার দেখে দর্শকদের বোঝার উপায় নেই যে ছবিত...
2,2,2,"[('কিংবা', 'O'), ('পিতা', 'O'), ('মাতা', 'O'),...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...","['কিংবা', 'পিতা', 'মাতা', 'কন্যা', 'ছেলে', 'ভা...",কিংবা পিতা মাতা কন্যা ছেলে ভাই বোন স্বামী স্ত্...
3,3,3,"[('কিন্তু', 'O'), ('আজব', 'O'), ('ব্যাপার', 'O...","['O', 'O', 'O', 'O', 'O', 'O']","['কিন্তু', 'আজব', 'ব্যাপার', 'বাস্তবে', 'এমনটা...",কিন্তু আজব ব্যাপার বাস্তবে এমনটা হয়নি
4,4,4,"[('বাংলাদেশও', 'B-LOC'), ('এর', 'O'), ('ব্যতিক...","['B-LOC', 'O', 'O', 'O']","['বাংলাদেশও', 'এর', 'ব্যতিক্রম', 'নয়']",বাংলাদেশও এর ব্যতিক্রম নয়
...,...,...,...,...,...,...
22139,22139,22139,"[('বাংলাদেশ', 'B-ORG'), ('ব্যাংকের', 'I-ORG'),...","['B-ORG', 'I-ORG', 'O', 'O', 'O', 'O', 'O', 'O']","['বাংলাদেশ', 'ব্যাংকের', 'অধীনে', 'একটি', 'তদন...",বাংলাদেশ ব্যাংকের অধীনে একটি তদন্ত কমিটি কাজ করছে
22140,22140,22140,"[('সঠিক', 'O'), ('তথ্য', 'O'), ('পাওয়া', 'O'),...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...","['সঠিক', 'তথ্য', 'পাওয়া', 'গেলে', 'জড়িতদের', '...",সঠিক তথ্য পাওয়া গেলে জড়িতদের বিরুদ্ধে ব্যবস্থা...
22141,22141,22141,"[('এ', 'O'), ('কারণে', 'O'), ('বাংলাদেশ', 'B-L...","['O', 'O', 'B-LOC', 'O', 'O', 'O', 'O', 'O', '...","['এ', 'কারণে', 'বাংলাদেশ', 'আন্তর্জাতিক', 'সম্...",এ কারণে বাংলাদেশ আন্তর্জাতিক সম্প্রদায়ের কাছে ...
22142,22142,22142,"[('সরকারের', 'O'), ('দক্ষ', 'O'), ('পরিচালনায়'...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...","['সরকারের', 'দক্ষ', 'পরিচালনায়', 'অর্থনীতির', ...",সরকারের দক্ষ পরিচালনায় অর্থনীতির সব সূচকে উল্ল...
22143,22143,22143,"[('সামাজিক', 'O'), ('সূচকগুলোর', 'O'), ('অগ্রগ...","['O', 'O', 'O', 'B-LOC', 'O', 'O', 'O', 'O', '...","['সামাজিক', 'সূচকগুলোর', 'অগ্রগতিতে', 'বাংলাদে...",সামাজিক সূচকগুলোর অগ্রগতিতে বাংলাদেশ প্রতিবেশী...